name: toolchain

on: 
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Prepare
        run: |
          sudo apt update
          sudo apt install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd \
            fakeroot kmod cpio git python3-docutils gettext automake autopoint \
            texinfo build-essential help2man pkg-config zlib1g-dev libgmp3-dev \
            libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget libc-dev-bin
      - name: Build
        run: |
          make -C toolchain build
          cd toolchain/toolchain-mipsel
          tar cJf ../mipsel-linux-uclibc-gcc12.tar.xz *
      - uses: actions/upload-artifact@v3
        with:
          name: toolchain
          path: toolchain/mipsel-linux-uclibc-gcc12.tar.xz
      - uses: svenstaro/upload-release-action@2.2.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: toolchain/mipsel-linux-uclibc-gcc12.tar.xz
          tag: toolchain
          overwrite: true